/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.DepartGBM;
import Modelo.EmpleGBM;
import Utilidad.UtilidadGBM;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author merjan
 */
public class InsertaEmpleGBM extends javax.swing.JFrame {
    private static final String NOT_SELECTABLE_OPTION1 = " Seleccione un oficio ";
    private static final String NOT_SELECTABLE_OPTION2 = " Seleccione un empleado ";
    private static final String NOT_SELECTABLE_OPTION3 = " Seleccione un departamento ";
    public static final String INSERTAR = "Insertar";
    public static final String NOMBRE = "Nombre";
    public static final String OFICIO = "Oficio";
    public static final String DIRECTOR = "Director";
    public static final String SALARIO = "Salario";
    public static final String COMISIÓN = "Comisión";
    public static final String DEPARTAMENTO = "Departamento";
    public static final String T = "0";

    /**
     * Creates new form InsertaEmpleGBM
     */
    public InsertaEmpleGBM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        List<String> listaoficio  = EmpleGBM.obtenerOficio();
        List<String> listadir  = EmpleGBM.obtenerDir();
        List<String> listadep  = DepartGBM.consultaDept();

        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<String>(){
        boolean selectionAllowed = true;
        @Override
        public void setSelectedItem(Object anObject) {
        if (!NOT_SELECTABLE_OPTION1.equals(anObject)) {
            super.setSelectedItem(anObject);
        } else if (selectionAllowed) {
            // Allow this just once
            selectionAllowed = false;
            super.setSelectedItem(anObject);
        }
      }});
        jComboBox1.addItem(NOT_SELECTABLE_OPTION1);

        for (String ofi:listaoficio) {
            jComboBox1.addItem(ofi);
        }

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<String>(){
            boolean selectionAllowed = true;
            @Override
            public void setSelectedItem(Object anObject) {
                if (!NOT_SELECTABLE_OPTION2.equals(anObject)) {
                    super.setSelectedItem(anObject);
                } else if (selectionAllowed) {
                    // Allow this just once
                    selectionAllowed = false;
                    super.setSelectedItem(anObject);
                }
            }});
        jComboBox2.addItem(NOT_SELECTABLE_OPTION2);
        for (String dir:listadir) {
            jComboBox2.addItem(dir);
        }

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<String>(){
            boolean selectionAllowed = true;
            @Override
            public void setSelectedItem(Object anObject) {
                if (!NOT_SELECTABLE_OPTION3.equals(anObject)) {
                    super.setSelectedItem(anObject);
                } else if (selectionAllowed) {
                    // Allow this just once
                    selectionAllowed = false;
                    super.setSelectedItem(anObject);
                }
            }});
        jComboBox3.addItem(NOT_SELECTABLE_OPTION3);
        for (String dep:listadep) {
            jComboBox3.addItem(dep);
        }

        jButton1.setText(INSERTAR);

        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int dir= EmpleGBM.obtenerNumDir(jComboBox2.getSelectedItem().toString());
                int dep_num= DepartGBM.consultaDeptNo(jComboBox3.getSelectedItem().toString());
                System.out.println(jComboBox1.getSelectedIndex());
                if (UtilidadGBM.JFEsvacio(jTextField2)) {
                    jTextField2.setText(T);
                 }if (UtilidadGBM.JFEsvacio(jTextField3)) {
                    jTextField3.setText(T);
                 }
                 if (UtilidadGBM.JFEsvacio(jTextField1)) {
                        jTextField1.setText(null);
                 }else if(jComboBox1.getSelectedItem().equals(NOT_SELECTABLE_OPTION1)) {
                 }else if(jComboBox2.getSelectedItem().equals(NOT_SELECTABLE_OPTION2)) {
                 }else if(jComboBox3.getSelectedItem().equals(NOT_SELECTABLE_OPTION3)) {
                 }else {
                    EmpleGBM.insertaEmp(
                            jTextField1.getText(),
                            jComboBox1.getSelectedItem().toString(),
                            dir,
                            Integer.parseInt(jTextField2.getText()),
                            Integer.parseInt(jTextField3.getText()),
                            dep_num
                            );
                 }
            }
        });

        jLabel1.setText(NOMBRE);

        jLabel2.setText(OFICIO);

        jLabel3.setText(DIRECTOR);

        jLabel4.setText(SALARIO);

        jLabel5.setText(COMISIÓN);

        jLabel6.setText(DEPARTAMENTO);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
